export const environment = {
  apiUrl: '...thisWontBeUsedBecauseItIsOverwrittenByTheEnvironmentSpecificFileInAngulardotJsonSimplyWhenServingAppWriteAflagdashdashConfigurationProductionOrDashDashConfigurationDevelopmentToUseTheEnvironmentSpecificFile...',
};
